precompile(lineplot, (Vector{Function},))
precompile(lineplot, (Vector{Function}, Int64, Int64,))
precompile(lineplot, (Vector{Float64}, ))
precompile(lineplot, (Vector{Float64}, Vector{Float64},))
precompile(scatterplot, (Vector{Float64}, ))
precompile(scatterplot, (Vector{Float64}, Vector{Float64},))
precompile(spy, (SparseMatrixCSC{Float64,Int64},))
precompile(spy, (Matrix{Float64},))
precompile(spy, (Matrix{Int64},))
precompile(BrailleCanvas, (Int64, Int64,))
precompile(AsciiCanvas, (Int64, Int64,))
precompile(Plot, (BrailleCanvas,))
precompile(Plot, (AsciiCanvas,))
precompile(Plot, (Vector{Float64}, Vector{Float64}, Type{BrailleCanvas}))
precompile(Plot, (Vector{Float64}, Vector{Float64}, Type{AsciiCanvas}))
precompile(Base.show, (Base.TTY, Plot{BrailleCanvas}))
precompile(Base.show, (Base.TTY, Plot{AsciiCanvas}))
precompile(printrow, (Base.TTY, BrailleCanvas, Int64))
precompile(printrow, (Base.TTY, AsciiCanvas, Int64))
