name: invalidations

on:
  pull_request:
  push:
   branches: [main]

concurrency: 
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
    - uses: julia-actions/setup-julia@latest
      with:
        version: '1'
    - uses: actions/checkout@v3
    - uses: julia-actions/julia-buildpkg@latest
    - uses: julia-actions/julia-invalidations@v1
      id: invs_pr

    - uses: actions/checkout@v3
      with:
        ref: 'main'
    - uses: julia-actions/julia-buildpkg@latest
    - uses: julia-actions/julia-invalidations@v1
      id: invs_main

    - name: Report invalidation counts
      run: |
        echo "Invalidations on main: ${{ steps.invs_main.outputs.total }} (${{ steps.invs_main.outputs.deps }} via deps)"
        echo "This branch: ${{ steps.invs_pr.outputs.total }} (${{ steps.invs_pr.outputs.deps }} via deps)"
      shell: bash
    - name: PR doesn't increase number of invalidations
      run: |
        if (( ${{ steps.invs_pr.outputs.total }} > ${{ steps.invs_main.outputs.total }} )); then
            exit 1
        fi
      shell: bash
